<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.3" />
		<PackageReference Include="Microsoft.Identity.Web" Version="4.5.0" />
		<PackageReference Include="Microsoft.Identity.Web.UI" Version="4.5.0" />
		<PackageReference Include="MudBlazor" Version="9.1.0" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\ActiveWorkoutClasses.Application\ActiveWorkoutClasses.Application.csproj" />
    <ProjectReference Include="..\ActiveWorkoutClasses.ServiceDefaults\ActiveWorkoutClasses.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
